libPath: "./RenderMan/Builds/LinuxMakefile/build/librenderman.so"
vst: "podolski"

# Audio
sampleRate: 44100
bufferSize: 512
fftSize: 512

# Midi
midiNote: 72
midiVelocity: 127
noteLength: 1.0
renderLength: 5.0